(function () {
  "use strict";
  const core = window.SuzyValuationCore;
  if (!core) return;
  const STORAGE_KEY = "suzy-valuation-v1";
  const $ = id => document.getElementById(id);
  const INTERPRETATION_LABELS = Object.freeze({
    REASONABLE_RANGE: "Faixa razoável sob premissas declaradas",
    OVERSTATED_ASSUMPTIONS: "Premissas superestimadas / agressivas",
    INSUFFICIENT_EVIDENCE: "Evidência insuficiente para concluir"
  });
  const DRIVER_LABELS = Object.freeze({
    DISCOUNT_RATE:"Taxa de desconto", TERMINAL_GROWTH:"Crescimento terminal", MARGIN_ASSUMPTION:"Margem projetada", CAPITAL_STRUCTURE:"Estrutura de capital",
    CYCLICAL_EARNINGS:"Lucro cíclico", COMPARABILITY:"Comparabilidade", NONRECURRING_ITEM:"Item não recorrente", NEGATIVE_FCF:"FCF negativo",
    TERMINAL_VALUE_WEIGHT:"Peso do valor terminal", UNIT_MISMATCH:"Incompatibilidade EV/equity", DILUTION:"Diluição", SCENARIO_SENSITIVITY:"Sensibilidade de cenários"
  });
  const ACTION_LABELS = Object.freeze({
    RUN_SENSITIVITY:"Rodar sensibilidade", RECALCULATE_WACC:"Recalcular taxa de desconto", NORMALIZE_MARGIN:"Normalizar margem", RECONCILE_NET_DEBT:"Reconciliar dívida líquida",
    NORMALIZE_CYCLE:"Normalizar ciclo", REBUILD_PEER_SET:"Reconstruir pares", REMOVE_NONRECURRING:"Excluir não recorrentes", CHECK_FCF_PATH:"Verificar trajetória do FCF",
    EXTEND_EXPLICIT_PERIOD:"Estender período explícito", RECONCILE_EV_EQUITY:"Reconciliar EV até equity", CHECK_DILUTED_SHARES:"Verificar ações diluídas", USE_SCENARIO_RANGE:"Usar faixa de cenários"
  });
  const SOURCE_LABELS = Object.freeze(Object.fromEntries(core.SOURCES.map(source => [source.id, source.title])));
  let state = loadState(); let session=null; let sessionId=""; let currentIndex=0; let locked=false; let sessionComplete=false;
  function loadState(){try{return core.normalizeState(JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}"));}catch(error){console.warn("Histórico de valuation inválido foi ignorado.",error);return core.normalizeState({});}}
  function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function currentAttempts(){return state.history.filter(a=>a.sessionId===sessionId);}
  function optionMarkup(items,labels){return '<option value="">Selecione</option>'+items.map(item=>`<option value="${item}">${labels[item]}</option>`).join("");}
  function fillOptions(){ $("caseInterpretation").innerHTML=optionMarkup(core.INTERPRETATIONS,INTERPRETATION_LABELS); $("caseDriver").innerHTML=optionMarkup(core.DRIVERS,DRIVER_LABELS); $("caseAction").innerHTML=optionMarkup(core.ACTIONS,ACTION_LABELS); $("caseSource").innerHTML='<option value="">Selecione</option>'+core.SOURCES.map(s=>`<option value="${s.id}">${s.title}</option>`).join(""); }
  function clearForm(){ $("caseForm").reset(); ["caseInterpretation","caseDriver","caseAction","caseSource"].forEach(id=>{$(id).value="";}); $("caseFeedback").textContent=""; $("caseResult").hidden=true; $("hardViolation").hidden=true; locked=false; [...$("caseForm").elements].forEach(el=>{el.disabled=false;}); }
  function renderCase(){const item=session.cases[currentIndex];clearForm();$("caseProgress").textContent=`CASO ${currentIndex+1} DE ${core.REQUIRED_CASES}`;$("caseLab").dataset.caseId=item.id;$("caseTitle").textContent=item.title;$("caseFacts").innerHTML=item.facts.map(f=>`<li>${f}</li>`).join("");$("nextCase").textContent=currentIndex===session.cases.length-1?"VER RESULTADO DA SESSÃO":"PRÓXIMO CASO";renderKpis();}
  function renderKpis(){const s=core.evaluateSession(currentAttempts());$("kpiCases").textContent=`${s.completed}/${s.required}`;$("kpiAverage").textContent=String(s.average);$("kpiViolations").textContent=String(s.hardViolations);$("kpiStatus").textContent=state.passed?"E3 APROVADO":"EM FORMAÇÃO";$("kpiBest").textContent=`melhor média: ${state.bestAverage}`;}
  function renderHistory(){const history=[...state.history].reverse();$("historyBody").innerHTML=history.length?history.map(a=>{const item=core.findCase(a.caseId);const date=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(a.timestamp));return `<tr><td>${date}</td><td>${a.seed}</td><td>${item?.title||a.caseId}</td><td class="${a.passed?"pass":"fail"}">${a.score}</td><td>${a.hardViolation?"SIM":"NÃO"}</td></tr>`;}).join(""):'<tr><td colspan="5" class="empty">Nenhuma resposta registrada.</td></tr>';}
  function startSession(shouldScroll=true){const seed=Number($("sessionSeed").value)||1;session=core.createSession(seed);sessionId=`valuation-${session.seed}-${Date.now()}`;currentIndex=0;sessionComplete=false;state=core.normalizeState({...state,lastSeed:session.seed});saveState();$("sessionSeed").value=String(session.seed);$("sessionLabel").textContent=`Sessão ${session.seed}: seis variantes selecionadas.`;renderCase();if(shouldScroll)$("caseLab").scrollIntoView({behavior:"smooth",block:"start"});}
  function submitCase(event){event.preventDefault();if(locked)return;const item=session.cases[currentIndex];const answer={interpretation:$("caseInterpretation").value,driver:$("caseDriver").value,action:$("caseAction").value,source:$("caseSource").value,rationale:$("caseRationale").value};if(!answer.interpretation||!answer.driver||!answer.action||!answer.source||!answer.rationale.trim()){$("caseFeedback").textContent="Preencha os cinco campos antes de avaliar.";return;}const grade=core.gradeCase(item.id,answer);state=core.recordAttempt(state,{sessionId,seed:session.seed,caseId:item.id,answer,timestamp:new Date().toISOString()});saveState();locked=true;[...$("caseForm").elements].forEach(el=>{el.disabled=true;});$("caseScore").textContent=String(grade.score);$("caseResultState").textContent=grade.passed?"APROVADO":"REVISAR";$("caseResultState").className=grade.passed?"pass":"fail";$("caseChecks").innerHTML=grade.checks.map(c=>`<article class="check-card ${c.passed?"pass":"fail"}"><strong>${c.passed?`+${c.points}`:"+0"} • ${c.label}</strong><span>${c.passed?"Critério atendido":"Critério não atendido"}</span></article>`).join("");$("hardViolation").hidden=!grade.hardViolation;$("hardViolation").textContent=grade.hardViolation?`VIOLAÇÃO DURA: ${grade.hardViolation}`:"";$("caseExplanation").textContent=grade.explanation;$("caseExpected").textContent=`Resposta esperada: ${INTERPRETATION_LABELS[grade.expectedInterpretation]}; ${DRIVER_LABELS[grade.expectedDriver]}; ${ACTION_LABELS[grade.expectedAction]}; ${SOURCE_LABELS[grade.expectedSource]}.`;$("caseResult").hidden=false;$("caseFeedback").textContent="Resposta travada. A nota mede qualidade das premissas e reconciliação; não prevê preço nem recomenda operação.";renderKpis();renderHistory();}
  function nextCase(){if(sessionComplete){$("sessionSeed").value=String(session.seed+1);startSession();return;}if(!locked)return;if(currentIndex<session.cases.length-1){currentIndex+=1;renderCase();return;}const s=core.evaluateSession(currentAttempts());$("sessionLabel").textContent=s.passed?`Sessão aprovada: média ${s.average}, sem violação dura.`:`Sessão concluída sem aprovação: média ${s.average}, ${s.hardViolations} violação(ões) dura(s).`;$("nextCase").textContent="INICIAR NOVA SESSÃO";sessionComplete=true;renderKpis();}
  function format(value,suffix=""){return value===null||value===undefined?"N/A":`${Number(value).toFixed(2)}${suffix}`;}
  function calculateSnapshot(event){event.preventDefault();const s=core.summarizeValuationSnapshot({fcf1:$("valFcf1").value,fcf2:$("valFcf2").value,fcf3:$("valFcf3").value,discountRate:$("valDiscountRate").value,terminalGrowth:$("valTerminalGrowth").value,netDebt:$("valNetDebt").value,dilutedShares:$("valShares").value});if(!s.valid){["valEnterprise","valEquity","valPerShare","valTerminalWeight"].forEach(id=>{$(id).textContent="N/A";});$("valFeedback").textContent="Modelo inválido: a taxa de desconto precisa ser maior que o crescimento terminal. Reveja as premissas antes de calcular.";return;}$("valEnterprise").textContent=format(s.enterpriseValue);$("valEquity").textContent=format(s.equityValue);$("valPerShare").textContent=format(s.valuePerShare);$("valTerminalWeight").textContent=format(s.terminalWeight,"%");$("valFeedback").textContent="Snapshot calculado. O resultado é sensível às premissas e deve ser tratado como cenário educacional, nunca como preço futuro garantido.";}
  fillOptions();$("valuationForm").addEventListener("submit",calculateSnapshot);$("startSession").addEventListener("click",()=>startSession(true));$("caseForm").addEventListener("submit",submitCase);$("nextCase").addEventListener("click",nextCase);$("clearHistory").addEventListener("click",()=>{if(!window.confirm("Limpar todo o histórico local desta trilha?"))return;state=core.normalizeState({lastSeed:state.lastSeed});saveState();renderHistory();renderKpis();});$("sessionSeed").value=String(state.lastSeed||20260815);renderHistory();startSession(false);
})();
